### ISSUE TITLE
Pd Bulk Discrepancy between Minimized Structure and non-Minimized Structure

### ISSUE THREAD

**Issue by yanxon** [yanxon/diffusion#3]
Hi @timfrol

I re run the 600 K for the non minimized structure.
![Figure_1](https://user-images.githubusercontent.com/32254481/69290506-0808c500-0bb5-11ea-8b0b-2c4c817642a8.png)

I also plot the volume vs. number of steps:
![volume](https://user-images.githubusercontent.com/32254481/69290736-bad92300-0bb5-11ea-865d-867771f1c580.png)
I think they are in different in structure.

**Comment by timfrol** [comment]
@yanxon 

this is good progress, Howard. 

We must figure out what the difference is and why it occurs before moving to GBs. It has a clear effect on diffusivity. You can plot energies as well. I assume that the temperatures were the same.

**Comment by yanxon** [comment]
@timfrol 

For some reason, I didn't output the energy. I will run both again. What are the other thermodynamics properties that are important?

I suppose pressure, total energy, & pot. energy.

**Comment by timfrol** [comment]
@yanxon 

your pressure should be zero. If temperature was the same, energy and potential energy should be the same or have the same difference. I assume you checked that you have the same number of Pd and the same numer of H atoms.

**Comment by yanxon** [comment]
@timfrol 

> @yanxon
> 
> your pressure should be zero. If temperature was the same, energy and potential energy should be the same or have the same difference. I assume you checked that you have the same number of Pd and the same numer of H atoms.

The total atoms (both Pd and H) are the same even after the calculation is finished.

**Comment by yanxon** [comment]
@timfrol 

Here are the thermodynamics plots:
1. Pressure
![pressure](https://user-images.githubusercontent.com/32254481/69505946-479b1e00-0ee1-11ea-8f32-92e107af15aa.png)
2. Pot Energy
![potE](https://user-images.githubusercontent.com/32254481/69505966-52ee4980-0ee1-11ea-9851-50396fb4f599.png)
3. Total E
![TotalE](https://user-images.githubusercontent.com/32254481/69505969-597cc100-0ee1-11ea-97ca-00030ed1d9af.png)
4. Volume
![volume](https://user-images.githubusercontent.com/32254481/69505976-5e417500-0ee1-11ea-9beb-ad117e90b333.png)

I'm not sure where to look at this point. Why does the discrepancy exist between the non-minimized and the minimized structures? 
- According to the LAMMPS output, all atoms (Pd and H) after the simulation are retained. 
- All I can think of the Pd are at different structures.

**Comment by timfrol** [comment]
@yanxon 

all suggest that you have different structures. Could you please send me final snapshots from each run. I would like to examine the structure with ovito.

**Comment by yanxon** [comment]
@timfrol 

I will send them tomorrow. I realize I didn't dump Pd (only H).

**Comment by timfrol** [comment]
sounds good

**Comment by yanxon** [comment]
@timfrol 

I just gave you the final structures of the NPT simulations. One is for minimized PdH (final_min_600K.chkpt) and the other is for non-minimized PdH structure (final_non_600K.chkpt). Please check it out.

**Comment by yanxon** [comment]
@timfrol 

I ran a space group analyzer with Pymatgen. Here is the script:

```
from pymatgen.io.lammps.data import LammpsData
from pymatgen.symmetry.analyzer import SpacegroupAnalyzer

crystal = LammpsData.from_file("Pd.dump", atom_style='atomic')

c = SpacegroupAnalyzer(crystal.structure, 0.01, 50).get_space_group_number()
```

Apparently the `Pd.dump` that I generated with lammps is not FCC Pd, but rather it has space group of 215. After minimization, the `PdH.min.dump` has no symmetry (SG=1). I suspect that after minimization of PdH, the structure become more of FCC Pd. Another possibility is that the PdH has mixed phases between alpha and beta phase after the minimization. Therefore, `PdH.min.dump`'s symmetry can't be detected.

Maybe, I will try again with the real FCC Pd structure.

**Comment by yanxon** [comment]
@timfrol 

Actually I have a statement. Palladium retains the FCC structure both in alpha phase and beta phase. Is this correct? Perhaps, Palladium is bcc in beta phase, isn't it?

**Comment by timfrol** [comment]
@yanxon 

Howard,

one of the easiest ways to check whether there is a problem with a simulation cell is to look at it with gnuplot or ovito. Please take a look at the structures you sent me.

Tim

**Comment by yanxon** [comment]
@timfrol 

I looked at it. I couldn't tell the difference between the two. It was because I looked at it at 3D view.

Now I'm looking at the orthonormal perspective, I can see clearly what the minimized PdH has some sort of symmetry and the non minimized PdH doesn't have any symmetry.

So, the non-minimized PdH melted?

**Comment by timfrol** [comment]
@yanxon 

very good Howard. Yes, one structure is still fcc, the other one is completely amorphous or liquid. Somehow the structure got completely destroyed during the MD run after the atoms were inserted. 

My initial guess is that the insertion procedure should be changed, perhaps by using different locations. The good news is that the minimization seems to help, but honestly, if you insert in proper places there should not be any different. 

It is important to track changes like this, we don't want the insertion of H atoms to destroy the GB structure.

**Comment by yanxon** [comment]
@timfrol 

I see. I'm actually running 2 more simulations. As I said before, the starting structure that I used is not FCC Pd, but Pd with space group (215). Now, I minimized the Pd-215 to Pd-225 before adding hydrogen.

It's possible that Pd-215 and Pd-225 have different melting points. The calculations should be done in 1 1/2 hours. 

If this is true, then I suspect that Pd-225 should give the same diffusivity whether it is minimized or not after the hydrogen is added.

**Comment by yanxon** [comment]
@timfrol 

I think you're right. The insertion of hydrogen matters.

Here is the result of the two-step minimization. First minimization is of the Pd structure, and the second minimization occurs after the hydrogen insertion:
![msd](https://user-images.githubusercontent.com/32254481/69588719-627f9800-0f9e-11ea-9071-678f534a3704.png)
Regardless, if the Pd structure is minimized or not, the Pd melts if there's no minimization after hydrogen atoms are inserted.

**Comment by timfrol** [comment]
@yanxon 

Howard, it sounds like you are doing something more complicated than necessary. 
fcc Pd is easy to make with lammps, your Pd GBs are already made. Do worry about doing a lot of complex analysis which we will not use later. We found the issue, I think it is ok to move on.

Tim

**Comment by timfrol** [comment]
@yanxon 

this is good, but it also may suggest that the original location of the H atoms may not be the ideal one. I have inserted Cu in Cu and W in W, and when done carefully it works and I did not use relaxation. 

On the other hand I never inserted that many atoms at one time. Perhaps this 2 step minimization procedure is a good idea.

**Comment by timfrol** [comment]
@yanxon 

why dont we proceed to GBs and use this procedure to insert atoms.

Can I suggest that you start with pure PD, SK GB, then insert H atoms and relax at 0K. No need to do MD steps, just want to see that the GB structure survivies the insertion. Send me the structures after you make them, I will take a look. Perhaps you could upload them to github.

Tim
